export type ImportantDateSeverity = "Low" | "Medium" | "High" | "Critical";

export type ImportantDateRow = {
  id: string;
  alertType: string;
  trigger: string;
  severity: ImportantDateSeverity;
  audience: string;
  message: string;
  actionRequired: string;
};

/** Built-in catalog rows (stable ids for hide/delete in browser storage). */
export const IMPORTANT_DATES_CATALOG: ImportantDateRow[] = [
  {
    id: "cat-001",
    alertType: "Low Exam Score",
    trigger: "Score < 75%",
    severity: "High",
    audience: "Instructor",
    message: "Student scored below passing threshold",
    actionRequired: "Assign remediation",
  },
  {
    id: "cat-002",
    alertType: "Failing Trend",
    trigger: "2+ low scores",
    severity: "High",
    audience: "Instructor",
    message: "Student showing downward performance trend",
    actionRequired: "Schedule meeting",
  },
  {
    id: "cat-003",
    alertType: "No Progress Update",
    trigger: "No grade in 7 days",
    severity: "Medium",
    audience: "Instructor",
    message: "No academic updates recorded",
    actionRequired: "Update progress report",
  },
  {
    id: "cat-004",
    alertType: "Attendance Issue",
    trigger: "< 80% attendance",
    severity: "High",
    audience: "Instructor/Admin",
    message: "Student below attendance requirement",
    actionRequired: "Review eligibility",
  },
  {
    id: "cat-005",
    alertType: "At-Risk Student",
    trigger: "Multiple flags triggered",
    severity: "Critical",
    audience: "Admin",
    message: "Student at risk of failure",
    actionRequired: "Intervention required",
  },
  {
    id: "cat-006",
    alertType: "Missing Patient Contacts",
    trigger: "Below required count",
    severity: "High",
    audience: "Instructor",
    message: "Student behind on patient contacts",
    actionRequired: "Assign additional shifts",
  },
  {
    id: "cat-007",
    alertType: "Skill Not Completed",
    trigger: "Required skill missing",
    severity: "High",
    audience: "Instructor",
    message: "Required skill not signed off",
    actionRequired: "Complete skill validation",
  },
  {
    id: "cat-008",
    alertType: "Clinical Hours Deficit",
    trigger: "Hours below target",
    severity: "High",
    audience: "Instructor",
    message: "Student behind on clinical hours",
    actionRequired: "Schedule makeup",
  },
  {
    id: "cat-009",
    alertType: "Preceptor Eval Missing",
    trigger: "Not submitted in 48 hrs",
    severity: "Medium",
    audience: "Instructor",
    message: "Preceptor evaluation missing",
    actionRequired: "Follow up",
  },
  {
    id: "cat-010",
    alertType: "No Team Lead Completed",
    trigger: "Internship requirement not met",
    severity: "Critical",
    audience: "Instructor/Admin",
    message: "Team lead requirement incomplete",
    actionRequired: "Assign team lead shift",
  },
  {
    id: "cat-011",
    alertType: "Missing Skills Sheet",
    trigger: "No submission",
    severity: "High",
    audience: "Instructor",
    message: "Skills sheet not completed",
    actionRequired: "Submit documentation",
  },
  {
    id: "cat-012",
    alertType: "Roster Not Submitted",
    trigger: "24 hrs post class",
    severity: "Critical",
    audience: "Instructor",
    message: "Course roster not submitted",
    actionRequired: "Complete roster",
  },
  {
    id: "cat-013",
    alertType: "Missing Course ID",
    trigger: "Field empty",
    severity: "High",
    audience: "Instructor",
    message: "Course ID not assigned",
    actionRequired: "Assign ID",
  },
  {
    id: "cat-014",
    alertType: "Audit Risk",
    trigger: "Multiple missing documents",
    severity: "Critical",
    audience: "Admin",
    message: "Course not audit compliant",
    actionRequired: "Fix immediately",
  },
  {
    id: "cat-015",
    alertType: "Form Incomplete",
    trigger: "Required fields blank",
    severity: "Medium",
    audience: "Instructor",
    message: "Form incomplete",
    actionRequired: "Complete form",
  },
  {
    id: "cat-016",
    alertType: "CoAEMSP Deadline Approaching",
    trigger: "30 days out",
    severity: "High",
    audience: "Admin",
    message: "Accreditation deadline approaching",
    actionRequired: "Prepare submission",
  },
  {
    id: "cat-017",
    alertType: "Annual Report Due",
    trigger: "14 days out",
    severity: "High",
    audience: "Admin",
    message: "Annual report due soon",
    actionRequired: "Submit report",
  },
  {
    id: "cat-018",
    alertType: "Site Visit Upcoming",
    trigger: "Scheduled date",
    severity: "Critical",
    audience: "Admin",
    message: "Site visit approaching",
    actionRequired: "Prepare audit docs",
  },
  {
    id: "cat-019",
    alertType: "Advisory Meeting Due",
    trigger: "Quarterly",
    severity: "Medium",
    audience: "Admin",
    message: "Advisory meeting required",
    actionRequired: "Schedule meeting",
  },
  {
    id: "cat-020",
    alertType: "Curriculum Review Due",
    trigger: "Annual",
    severity: "Medium",
    audience: "Admin",
    message: "Curriculum review required",
    actionRequired: "Conduct review",
  },
  {
    id: "cat-021",
    alertType: "Medical Director Review Due",
    trigger: "Scheduled interval",
    severity: "High",
    audience: "Admin",
    message: "Medical director review required",
    actionRequired: "Schedule review",
  },
  {
    id: "cat-022",
    alertType: "Protocol Review Expired",
    trigger: "Past due",
    severity: "Critical",
    audience: "Admin",
    message: "Protocols not reviewed",
    actionRequired: "Update protocols",
  },
  {
    id: "cat-023",
    alertType: "Skill Authorization Missing",
    trigger: "Not signed",
    severity: "High",
    audience: "Instructor/Admin",
    message: "Skill not authorized",
    actionRequired: "Obtain approval",
  },
  {
    id: "cat-024",
    alertType: "QA Case Review Due",
    trigger: "Monthly",
    severity: "Medium",
    audience: "Admin",
    message: "QA review required",
    actionRequired: "Conduct case review",
  },
  {
    id: "cat-025",
    alertType: "Instructor Certification Expiring",
    trigger: "30 days before expiration",
    severity: "High",
    audience: "Instructor/Admin",
    message: "Instructor certification expiring soon",
    actionRequired: "Renew certification",
  },
  {
    id: "cat-026",
    alertType: "Instructor Certification Expired",
    trigger: "Past expiration date",
    severity: "Critical",
    audience: "Admin",
    message: "Instructor certification expired",
    actionRequired: "Remove from teaching",
  },
  {
    id: "cat-027",
    alertType: "Instructor Monitoring Due",
    trigger: "Annual requirement",
    severity: "Medium",
    audience: "Admin",
    message: "Instructor monitoring required",
    actionRequired: "Schedule evaluation",
  },
  {
    id: "cat-028",
    alertType: "Instructor CE Due",
    trigger: "CE hours incomplete",
    severity: "Medium",
    audience: "Instructor",
    message: "Continuing education requirement not met",
    actionRequired: "Complete CE hours",
  },
  {
    id: "cat-029",
    alertType: "Instructor Alignment Expiring",
    trigger: "30 days before expiration",
    severity: "High",
    audience: "Instructor/Admin",
    message: "Instructor alignment expiring",
    actionRequired: "Renew alignment",
  },
  {
    id: "cat-030",
    alertType: "NREMT Application Not Submitted",
    trigger: "Past recommended date",
    severity: "High",
    audience: "Instructor",
    message: "Student has not applied for NREMT",
    actionRequired: "Assist with application",
  },
  {
    id: "cat-031",
    alertType: "Authorization to Test Missing",
    trigger: "No ATT received",
    severity: "High",
    audience: "Instructor",
    message: "Student not authorized to test",
    actionRequired: "Verify eligibility",
  },
  {
    id: "cat-032",
    alertType: "Psychomotor Exam Scheduled",
    trigger: "Upcoming exam",
    severity: "Medium",
    audience: "Instructor",
    message: "Psychomotor exam approaching",
    actionRequired: "Prepare student",
  },
  {
    id: "cat-033",
    alertType: "Cognitive Exam Window Open",
    trigger: "Active window",
    severity: "Medium",
    audience: "Instructor",
    message: "Cognitive exam window active",
    actionRequired: "Encourage testing",
  },
  {
    id: "cat-034",
    alertType: "State License Deadline",
    trigger: "Approaching deadline",
    severity: "High",
    audience: "Instructor/Admin",
    message: "Licensing deadline approaching",
    actionRequired: "Submit application",
  },
  {
    id: "cat-035",
    alertType: "Progress Report Due",
    trigger: "Scheduled interval",
    severity: "Medium",
    audience: "Instructor",
    message: "Progress report due",
    actionRequired: "Complete report",
  },
  {
    id: "cat-036",
    alertType: "Remediation Deadline",
    trigger: "Date reached",
    severity: "High",
    audience: "Instructor",
    message: "Remediation deadline reached",
    actionRequired: "Verify completion",
  },
  {
    id: "cat-037",
    alertType: "Final Grades Due",
    trigger: "End of course",
    severity: "High",
    audience: "Instructor",
    message: "Final grades must be submitted",
    actionRequired: "Submit grades",
  },
  {
    id: "cat-038",
    alertType: "Course Completion Deadline",
    trigger: "End date reached",
    severity: "Critical",
    audience: "Instructor/Admin",
    message: "Course must be closed out",
    actionRequired: "Finalize documentation",
  },
  {
    id: "cat-039",
    alertType: "Class Starting Soon",
    trigger: "24 hrs before class",
    severity: "Low",
    audience: "Instructor",
    message: "Upcoming course reminder",
    actionRequired: "Prepare materials",
  },
  {
    id: "cat-040",
    alertType: "Class Over Time",
    trigger: "Exceeds scheduled time",
    severity: "Medium",
    audience: "Instructor",
    message: "Class running behind schedule",
    actionRequired: "Adjust timeline",
  },
  {
    id: "cat-041",
    alertType: "Missing Equipment",
    trigger: "Pre-class checklist incomplete",
    severity: "Medium",
    audience: "Instructor",
    message: "Required equipment missing",
    actionRequired: "Obtain supplies",
  },
  {
    id: "cat-042",
    alertType: "System Sync Error",
    trigger: "Data not syncing",
    severity: "Critical",
    audience: "Admin",
    message: "System not syncing properly",
    actionRequired: "Investigate issue",
  },
  {
    id: "cat-043",
    alertType: "Missing Data Link",
    trigger: "Broken integration",
    severity: "High",
    audience: "Admin",
    message: "Data connection failure",
    actionRequired: "Reconnect system",
  },
  {
    id: "cat-044",
    alertType: "Duplicate Student Entry",
    trigger: "Duplicate detected",
    severity: "Low",
    audience: "Admin",
    message: "Duplicate student record found",
    actionRequired: "Merge or delete",
  },
];
